<a href="https://colab.research.google.com/github/Joaquin-Lobato-Adinolfi/TP_LMC_F1_Analysis/blob/main/TP_LMC_F1_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importacion de librerias y dataset

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**Ahora, importamos el dataset completo desde la pagina, con el formato que nos dan**

Observese, path funcionara para traer y luego leer los csv que contiene la descarga

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("rohanrao/formula-1-world-championship-1950-2020")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/rohanrao/formula-1-world-championship-1950-2020/24.archive...

100%|██████████| 6.28M/6.28M [00:00<00:00, 106MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/rohanrao/formula-1-world-championship-1950-2020/versions/24

El dataset contiene muchos csv pero seleccionaremos los necesarios para cumplir con nuestro cometido, necesitando tambien filtrarlos por años principalmente. Para ello, leeremos primero el csv completo y luego dejaremos uno filtrado con los datos necesitados.

**--------------------------------------------------------------------------------------------------------------------------------**

# Dataset

**--------------------------------------------------------------------------------------------------------------------------------**

## Races

In [49]:
# Todas las carreras
races_all = pd.read_csv(path + "/races.csv")
races_all

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,1140,2024,20,32,Mexico City Grand Prix,2024-10-27,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,2024-10-25,22:00:00,2024-10-26,17:30:00,2024-10-26,21:00:00,\N,\N
1121,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,2024-11-01,18:30:00,\N,\N,2024-11-02,18:00:00,2024-11-02,14:00:00
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,2024-11-21,06:00:00,2024-11-22,02:30:00,2024-11-22,06:00:00,\N,\N
1123,1143,2024,23,78,Qatar Grand Prix,2024-12-01,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,2024-11-29,17:30:00,\N,\N,2024-11-30,17:00:00,2024-11-30,13:00:00
1124,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,2024-12-06,13:00:00,2024-12-07,10:30:00,2024-12-07,14:00:00,\N,\N

In [50]:
# Las carreras de 2010 a 2024
races = races_all[races_all["year"] >= 2010]
races

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
336,337,2010,1,3,Bahrain Grand Prix,2010-03-14,12:00:00,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
337,338,2010,2,1,Australian Grand Prix,2010-03-28,06:00:00,http://en.wikipedia.org/wiki/2010_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
338,339,2010,3,2,Malaysian Grand Prix,2010-04-04,08:00:00,http://en.wikipedia.org/wiki/2010_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
339,340,2010,4,17,Chinese Grand Prix,2010-04-18,06:00:00,http://en.wikipedia.org/wiki/2010_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
340,341,2010,5,4,Spanish Grand Prix,2010-05-09,12:00:00,http://en.wikipedia.org/wiki/2010_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,1140,2024,20,32,Mexico City Grand Prix,2024-10-27,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,2024-10-25,22:00:00,2024-10-26,17:30:00,2024-10-26,21:00:00,\N,\N
1121,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,2024-11-01,18:30:00,\N,\N,2024-11-02,18:00:00,2024-11-02,14:00:00
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,2024-11-21,06:00:00,2024-11-22,02:30:00,2024-11-22,06:00:00,\N,\N
1123,1143,2024,23,78,Qatar Grand Prix,2024-12-01,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,2024-11-29,17:30:00,\N,\N,2024-11-30,17:00:00,2024-11-30,13:00:00
1124,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,2024-12-06,13:00:00,2024-12-07,10:30:00,2024-12-07,14:00:00,\N,\N

Procedemos a un analisis de las tablas obtenidas, tanto para un analisis preliminar, como para luego decidir que datos utilizar para nuestra busqueda

In [51]:
races.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
336,337,2010,1,3,Bahrain Grand Prix,2010-03-14,12:00:00,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
337,338,2010,2,1,Australian Grand Prix,2010-03-28,06:00:00,http://en.wikipedia.org/wiki/2010_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
338,339,2010,3,2,Malaysian Grand Prix,2010-04-04,08:00:00,http://en.wikipedia.org/wiki/2010_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
339,340,2010,4,17,Chinese Grand Prix,2010-04-18,06:00:00,http://en.wikipedia.org/wiki/2010_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
340,341,2010,5,4,Spanish Grand Prix,2010-05-09,12:00:00,http://en.wikipedia.org/wiki/2010_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [52]:
races.tail()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
1120,1140,2024,20,32,Mexico City Grand Prix,2024-10-27,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,2024-10-25,22:00:00,2024-10-26,17:30:00,2024-10-26,21:00:00,\N,\N
1121,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,2024-11-01,18:30:00,\N,\N,2024-11-02,18:00:00,2024-11-02,14:00:00
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,2024-11-21,06:00:00,2024-11-22,02:30:00,2024-11-22,06:00:00,\N,\N
1123,1143,2024,23,78,Qatar Grand Prix,2024-12-01,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,2024-11-29,17:30:00,\N,\N,2024-11-30,17:00:00,2024-11-30,13:00:00
1124,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,2024-12-06,13:00:00,2024-12-07,10:30:00,2024-12-07,14:00:00,\N,\N

In [53]:
#Dimensiones
print(f"La tabla races tiene {races.shape[0]} filas y {races.shape[1]} columnas")

La tabla races tiene 305 filas y 18 columnas

In [54]:
races.info()

<class 'pandas.core.frame.DataFrame'>
Index: 305 entries, 336 to 1124
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   raceId       305 non-null    int64
 1   year         305 non-null    int64
 2   round        305 non-null    int64
 3   circuitId    305 non-null    int64
 4   name         305 non-null    object
 5   date         305 non-null    object
 6   time         305 non-null    object
 7   url          305 non-null    object
 8   fp1_date     305 non-null    object
 9   fp1_time     305 non-null    object
 10  fp2_date     305 non-null    object
 11  fp2_time     305 non-null    object
 12  fp3_date     305 non-null    object
 13  fp3_time     305 non-null    object
 14  quali_date   305 non-null    object
 15  quali_time   305 non-null    object
 16  sprint_date  305 non-null    object
 17  sprint_time  305 non-null    object
dtypes: int64(4), object(14)
memory usage: 53.4+ KB

In [55]:
races.dtypes

raceId          int64
year            int64
round           int64
circuitId       int64
name           object
date           object
time           object
url            object
fp1_date       object
fp1_time       object
fp2_date       object
fp2_time       object
fp3_date       object
fp3_time       object
quali_date     object
quali_time     object
sprint_date    object
sprint_time    object
dtype: object

In [56]:
races.isnull().sum()

raceId         0
year           0
round          0
circuitId      0
name           0
date           0
time           0
url            0
fp1_date       0
fp1_time       0
fp2_date       0
fp2_time       0
fp3_date       0
fp3_time       0
quali_date     0
quali_time     0
sprint_date    0
sprint_time    0
dtype: int64

In [57]:
races.describe().round(0)

       raceId    year  round  circuitId
count   305.0   305.0  305.0      305.0
mean    953.0  2017.0   11.0       25.0
std     179.0     4.0    6.0       25.0
min     337.0  2010.0    1.0        1.0
25%     899.0  2013.0    6.0        7.0
50%     985.0  2017.0   11.0       15.0
75%    1064.0  2021.0   16.0       32.0
max    1144.0  2024.0   24.0       80.0

Conclusiones del analisis:

No se encontraron nulls, por lo que la tabla se encuentra completa. El describe no nos arroja datos importantes ya que realiza los analisis sobre int64, siendo estos solo de index o años, valores cuyas medidas estadisticas no son de uso en este analisis. Los otros datos son del tipo object, por eso no se les realiza un analisis estadistico con describe. Mas adelante, llegado el caso de necesitar hacer analisis sobre ellos, veremos la manera de cambiar su tipo de dato o aislar el dato necesario del mismo

**--------------------------------------------------------------------------------------------------------------------------------**

## Results

In [58]:
# Todos los resultados
results_all = pd.read_csv(path + "/results.csv")
results_all

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,26760,1144,825,210,20,14,16,16,16,0.0,57,\N,\N,57,1,1:25.637,222.002,11
26755,26761,1144,859,215,30,12,17,17,17,0.0,55,\N,\N,52,12,1:28.751,214.212,5
26756,26762,1144,822,15,77,9,\N,R,18,0.0,30,\N,\N,14,19,1:29.482,212.462,130
26757,26763,1144,861,3,43,20,\N,R,19,0.0,26,\N,\N,5,17,1:29.411,212.631,5
26758,26764,1144,815,9,11,10,\N,R,20,0.0,0,\N,\N,\N,0,\N,\N,4

In [59]:
# Los resultados de las carreras de 2010 a 2024
results = results_all[results_all['raceId'].isin(races['raceId'])]
results

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
20320,20323,337,4,6,8,3,1,1,1,25.0,49,1:39:20.396,5960396,45,1,1:58.287,191.706,1
20321,20324,337,13,6,7,2,2,2,2,18.0,49,+16.099,5976495,38,5,1:59.732,189.392,1
20322,20325,337,1,1,2,4,3,3,3,15.0,49,+23.182,5983578,42,4,1:59.560,189.665,1
20323,20326,337,20,9,5,1,4,4,4,12.0,49,+38.799,5999195,32,12,2:00.218,188.627,1
20324,20327,337,3,131,4,5,5,5,5,10.0,49,+40.213,6000609,45,13,2:00.236,188.599,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,26760,1144,825,210,20,14,16,16,16,0.0,57,\N,\N,57,1,1:25.637,222.002,11
26755,26761,1144,859,215,30,12,17,17,17,0.0,55,\N,\N,52,12,1:28.751,214.212,5
26756,26762,1144,822,15,77,9,\N,R,18,0.0,30,\N,\N,14,19,1:29.482,212.462,130
26757,26763,1144,861,3,43,20,\N,R,19,0.0,26,\N,\N,5,17,1:29.411,212.631,5
26758,26764,1144,815,9,11,10,\N,R,20,0.0,0,\N,\N,\N,0,\N,\N,4

Procedemos a un analisis de las tablas obtenidas, tanto para un analisis preliminar, como para luego decidir que datos utilizar para nuestra busqueda

In [60]:
results.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
20320,20323,337,4,6,8,3,1,1,1,25.0,49,1:39:20.396,5960396,45,1,1:58.287,191.706,1
20321,20324,337,13,6,7,2,2,2,2,18.0,49,+16.099,5976495,38,5,1:59.732,189.392,1
20322,20325,337,1,1,2,4,3,3,3,15.0,49,+23.182,5983578,42,4,1:59.560,189.665,1
20323,20326,337,20,9,5,1,4,4,4,12.0,49,+38.799,5999195,32,12,2:00.218,188.627,1
20324,20327,337,3,131,4,5,5,5,5,10.0,49,+40.213,6000609,45,13,2:00.236,188.599,1

In [61]:
results.tail()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
26754,26760,1144,825,210,20,14,16,16,16,0.0,57,\N,\N,57,1,1:25.637,222.002,11
26755,26761,1144,859,215,30,12,17,17,17,0.0,55,\N,\N,52,12,1:28.751,214.212,5
26756,26762,1144,822,15,77,9,\N,R,18,0.0,30,\N,\N,14,19,1:29.482,212.462,130
26757,26763,1144,861,3,43,20,\N,R,19,0.0,26,\N,\N,5,17,1:29.411,212.631,5
26758,26764,1144,815,9,11,10,\N,R,20,0.0,0,\N,\N,\N,0,\N,\N,4

In [62]:
#Dimensiones
print(f"La tabla results tiene {results.shape[0]} filas y {results.shape[1]} columnas")

La tabla results tiene 6436 filas y 18 columnas

In [63]:
results.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6436 entries, 20320 to 26758
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         6436 non-null   int64
 1   raceId           6436 non-null   int64
 2   driverId         6436 non-null   int64
 3   constructorId    6436 non-null   int64
 4   number           6436 non-null   object
 5   grid             6436 non-null   int64
 6   position         6436 non-null   object
 7   positionText     6436 non-null   object
 8   positionOrder    6436 non-null   int64
 9   points           6436 non-null   float64
 10  laps             6436 non-null   int64
 11  time             6436 non-null   object
 12  milliseconds     6436 non-null   object
 13  fastestLap       6436 non-null   object
 14  rank             6436 non-null   object
 15  fastestLapTime   6436 non-null   object
 16  fastestLapSpeed  6436 non-null   object
 17  statusId         6436 non-null   int64
dtypes: float64(1), int64(8), object(9)
memory usage: 955.3+ KB

In [64]:
results.dtypes

resultId             int64
raceId               int64
driverId             int64
constructorId        int64
number              object
grid                 int64
position            object
positionText        object
positionOrder        int64
points             float64
laps                 int64
time                object
milliseconds        object
fastestLap          object
rank                object
fastestLapTime      object
fastestLapSpeed     object
statusId             int64
dtype: object

In [65]:
results.isnull().sum()

resultId           0
raceId             0
driverId           0
constructorId      0
number             0
grid               0
position           0
positionText       0
positionOrder      0
points             0
laps               0
time               0
milliseconds       0
fastestLap         0
rank               0
fastestLapTime     0
fastestLapSpeed    0
statusId           0
dtype: int64

In [66]:
results.describe().round(2)

,resultId,raceId,driverId,constructorId,grid,positionOrder,points,laps,statusId
count,6436.00,6436.00,6436.00,6436.00,6436.00,6436.00,6436.00,6436.00,6436.00
mean,23543.37,942.87,538.66,71.01,10.87,11.11,4.81,53.26,9.34
std,1860.50,186.14,386.44,85.71,6.24,6.20,7.14,17.86,20.00
min,20323.00,337.00,1.00,1.00,0.00,1.00,0.00,0.00,1.00
25%,21931.75,890.00,20.00,5.00,6.00,6.00,0.00,51.00,1.00
50%,23542.50,977.00,817.00,10.00,11.00,11.00,0.00,56.00,1.00
75%,25155.25,1060.00,835.00,131.00,16.00,16.00,8.00,66.00,11.00
max,26764.00,1144.00,862.00,215.00,24.00,24.00,50.00,87.00,141.00

Conclusiones del analisis:

Si bien no se muestran nulls, es de notar que hay valores marcados con "\N". Esto muestra o que no hay datos o que no han sido tomados. Nos iclinamamos a que no han sido tomados ya que, mas adelante, nos sera mas util analizar solo los datos de corredores que hayan finalizado la carrera (status = 1) y en los casos que figuran con "\N" se puede ver que el status no es ese, denotando una no finalizacion de carrera.

**--------------------------------------------------------------------------------------------------------------------------------**

## Drivers

In [67]:
# Todos los corredores
drivers_all = pd.read_csv(path + "/drivers.csv")
drivers_all

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,30,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,38,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto
860,862,doohan,61,DOO,Jack,Doohan,2003-01-20,Australian,http://en.wikipedia.org/wiki/Jack_Doohan

In [68]:
# Los corredores de las carreras filtradas
drivers = drivers_all[drivers_all['driverId'].isin(results['driverId'])]
drivers

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,30,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,38,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto
860,862,doohan,61,DOO,Jack,Doohan,2003-01-20,Australian,http://en.wikipedia.org/wiki/Jack_Doohan

Procedemos a un analisis de las tablas obtenidas, tanto para un analisis preliminar, como para luego decidir que datos utilizar para nuestra busqueda

In [69]:
drivers.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [70]:
drivers.tail()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,30,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,38,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto
860,862,doohan,61,DOO,Jack,Doohan,2003-01-20,Australian,http://en.wikipedia.org/wiki/Jack_Doohan

In [71]:
#Dimensiones
print(f"La tabla results tiene {drivers.shape[0]} filas y {drivers.shape[1]} columnas")

La tabla results tiene 80 filas y 9 columnas

In [72]:
drivers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 80 entries, 0 to 860
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driverId     80 non-null     int64
 1   driverRef    80 non-null     object
 2   number       80 non-null     object
 3   code         80 non-null     object
 4   forename     80 non-null     object
 5   surname      80 non-null     object
 6   dob          80 non-null     object
 7   nationality  80 non-null     object
 8   url          80 non-null     object
dtypes: int64(1), object(8)
memory usage: 8.3+ KB

In [73]:
drivers.dtypes

driverId        int64
driverRef      object
number         object
code           object
forename       object
surname        object
dob            object
nationality    object
url            object
dtype: object

In [74]:
drivers.isnull().sum()

driverId       0
driverRef      0
number         0
code           0
forename       0
surname        0
dob            0
nationality    0
url            0
dtype: int64

In [75]:
drivers.describe()

         driverId
count   80.000000
mean   585.075000
std    374.120057
min      1.000000
25%     38.500000
50%    822.500000
75%    842.250000
max    862.000000

Conlusiones del analisis:

Nada notable, el describe no muestra nada. Los datos seran utiles para saber exactamente de que corredor hablamos cuando utilizamos sus datos.

**--------------------------------------------------------------------------------------------------------------------------------**

## Contructors

In [76]:
# Todas las escuderias
constructors_all = pd.read_csv(path + "/constructors.csv")
constructors_all

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
...,...,...,...,...,...
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
208,211,racing_point,Racing Point,British,http://en.wikipedia.org/wiki/Racing_Point_F1_Team
209,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
210,214,alpine,Alpine F1 Team,French,http://en.wikipedia.org/wiki/Alpine_F1_Team
211,215,rb,RB F1 Team,Italian,http://en.wikipedia.org/wiki/RB_Formula_One_Team

In [77]:
# Las escuderias de 2010 a 2024
constructors = constructors_all[constructors_all['constructorId'].isin(results['constructorId'])]
constructors

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
5,6,ferrari,Ferrari,Italian,http://en.wikipedia.org/wiki/Scuderia_Ferrari
8,9,red_bull,Red Bull,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing
9,10,force_india,Force India,Indian,http://en.wikipedia.org/wiki/Racing_Point_Forc...
14,15,sauber,Sauber,Swiss,http://en.wikipedia.org/wiki/Sauber_Motorsport
49,51,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...
115,117,aston_martin,Aston Martin,British,http://en.wikipedia.org/wiki/Aston_Martin_in_F...
129,131,mercedes,Mercedes,German,http://en.wikipedia.org/wiki/Mercedes-Benz_in_...
162,164,hrt,HRT,Spanish,http://en.wikipedia.org/wiki/Hispania_Racing
164,166,virgin,Virgin,British,http://en.wikipedia.org/wiki/Virgin_Racing
202,205,lotus_racing,Lotus,Malaysian,http://en.wikipedia.org/wiki/Lotus_Racing
203,206,marussia,Marussia,Russian,http://en.wikipedia.org/wiki/Marussia_F1
204,207,caterham,Caterham,Malaysian,http://en.wikipedia.org/wiki/Caterham_F1
205,208,lotus_f1,Lotus F1,British,http://en.wikipedia.org/wiki/Lotus_F1
206,209,manor,Manor Marussia,British,http://en.wikipedia.org/wiki/Manor_Motorsport
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
208,211,racing_point,Racing Point,British,http://en.wikipedia.org/wiki/Racing_Point_F1_Team
209,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
210,214,alpine,Alpine F1 Team,French,http://en.wikipedia.org/wiki/Alpine_F1_Team
211,215,rb,RB F1 Team,Italian,http://en.wikipedia.org/wiki/RB_Formula_One_Team

Procedemos a un analisis de las tablas obtenidas, tanto para un analisis preliminar, como para luego decidir que datos utilizar para nuestra busqueda

In [78]:
constructors.head()

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
5,6,ferrari,Ferrari,Italian,http://en.wikipedia.org/wiki/Scuderia_Ferrari

In [79]:
constructors.tail()

,constructorId,constructorRef,name,nationality,url
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
208,211,racing_point,Racing Point,British,http://en.wikipedia.org/wiki/Racing_Point_F1_Team
209,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
210,214,alpine,Alpine F1 Team,French,http://en.wikipedia.org/wiki/Alpine_F1_Team
211,215,rb,RB F1 Team,Italian,http://en.wikipedia.org/wiki/RB_Formula_One_Team

In [80]:
#Dimensiones
print(f"La tabla results tiene {constructors.shape[0]} filas y {constructors.shape[1]} columnas")

La tabla results tiene 23 filas y 5 columnas

In [81]:
constructors.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, 0 to 211
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   constructorId   23 non-null     int64
 1   constructorRef  23 non-null     object
 2   name            23 non-null     object
 3   nationality     23 non-null     object
 4   url             23 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.1+ KB

In [82]:
constructors.dtypes

constructorId      int64
constructorRef    object
name              object
nationality       object
url               object
dtype: object

In [83]:
constructors.isnull().sum()

constructorId     0
constructorRef    0
name              0
nationality       0
url               0
dtype: int64

In [84]:
constructors.describe()

       constructorId
count      23.000000
mean      120.869565
std        93.576563
min         1.000000
25%         9.500000
50%       164.000000
75%       208.500000
max       215.000000

Conclusiones del analisis:

Al igual que drivers, los datos se utilizaran para emparejar datos con escuderias luego

**--------------------------------------------------------------------------------------------------------------------------------**

## Qualifying

In [85]:
# Todas las qualis
qualifying_all = pd.read_csv(path + "/qualifying.csv")
qualifying_all

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236
...,...,...,...,...,...,...,...,...,...
10489,10547,1144,848,3,23,16,1:23.821,\N,\N
10490,10548,1144,855,15,24,17,1:23.880,\N,\N
10491,10549,1144,1,131,44,18,1:23.887,\N,\N
10492,10550,1144,861,3,43,19,1:23.912,\N,\N
10493,10551,1144,862,214,61,20,1:24.105,\N,\N

In [86]:
# Las qualis de 2010 a 2024
qualifying = qualifying_all[qualifying_all['raceId'].isin(races['raceId'])]
qualifying

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
3324,3326,337,20,9,5,1,1:55.029,1:53.883,1:54.101
3325,3327,337,13,6,7,2,1:55.313,1:54.331,1:54.242
3326,3328,337,4,6,8,3,1:54.612,1:54.172,1:54.608
3327,3329,337,1,1,2,4,1:55.341,1:54.707,1:55.217
3328,3330,337,3,131,4,5,1:55.463,1:54.682,1:55.241
...,...,...,...,...,...,...,...,...,...
10489,10547,1144,848,3,23,16,1:23.821,\N,\N
10490,10548,1144,855,15,24,17,1:23.880,\N,\N
10491,10549,1144,1,131,44,18,1:23.887,\N,\N
10492,10550,1144,861,3,43,19,1:23.912,\N,\N
10493,10551,1144,862,214,61,20,1:24.105,\N,\N

Procedemos a un analisis de las tablas obtenidas, tanto para un analisis preliminar, como para luego decidir que datos utilizar para nuestra busqueda

In [88]:
qualifying.head()

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
3324,3326,337,20,9,5,1,1:55.029,1:53.883,1:54.101
3325,3327,337,13,6,7,2,1:55.313,1:54.331,1:54.242
3326,3328,337,4,6,8,3,1:54.612,1:54.172,1:54.608
3327,3329,337,1,1,2,4,1:55.341,1:54.707,1:55.217
3328,3330,337,3,131,4,5,1:55.463,1:54.682,1:55.241

In [89]:
qualifying.tail()

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
10489,10547,1144,848,3,23,16,1:23.821,\N,\N
10490,10548,1144,855,15,24,17,1:23.880,\N,\N
10491,10549,1144,1,131,44,18,1:23.887,\N,\N
10492,10550,1144,861,3,43,19,1:23.912,\N,\N
10493,10551,1144,862,214,61,20,1:24.105,\N,\N

In [90]:
#Dimensiones
print(f"La tabla results tiene {qualifying.shape[0]} filas y {qualifying.shape[1]} columnas")

La tabla results tiene 6412 filas y 9 columnas

In [91]:
qualifying.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6412 entries, 3324 to 10493
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   qualifyId      6412 non-null   int64
 1   raceId         6412 non-null   int64
 2   driverId       6412 non-null   int64
 3   constructorId  6412 non-null   int64
 4   number         6412 non-null   int64
 5   position       6412 non-null   int64
 6   q1             6412 non-null   object
 7   q2             6390 non-null   object
 8   q3             6366 non-null   object
dtypes: int64(6), object(3)
memory usage: 500.9+ KB

In [92]:
qualifying.dtypes

qualifyId         int64
raceId            int64
driverId          int64
constructorId     int64
number            int64
position          int64
q1               object
q2               object
q3               object
dtype: object

In [93]:
qualifying.isnull().sum()

qualifyId         0
raceId            0
driverId          0
constructorId     0
number            0
position          0
q1                0
q2               22
q3               46
dtype: int64

In [95]:
qualifying.describe().round(2)

       qualifyId   raceId  driverId  constructorId   number  position
count    6412.00  6412.00   6412.00        6412.00  6412.00   6412.00
mean     7256.98   942.93    538.81          71.07    22.89     11.07
std      1965.43   186.45    386.40          85.72    21.85      6.17
min      3326.00   337.00      1.00           1.00     1.00      1.00
25%      5684.75   890.00     20.00           5.00     8.00      6.00
50%      7308.50   977.00    817.00          10.00    17.00     11.00
75%      8929.25  1060.00    835.00         131.00    27.00     16.00
max     10551.00  1144.00    862.00         215.00    99.00     24.00

Conclusiones del analisis:

Es de notar en este caso la aparicion de nulls en los datos. Puede deberse a retiros previos a las q2 y/o q3 de algun corredor, cosa que podemos corroborar luego cuando chequeemos carreras y qualis finalizadas.

**--------------------------------------------------------------------------------------------------------------------------------**

## Status

(Dato para filtrar excepciones)

In [87]:
status = pd.read_csv(path + "/status.csv")
status

     statusId          status
0           1        Finished
1           2    Disqualified
2           3        Accident
3           4       Collision
4           5          Engine
..        ...             ...
134       137          Damage
135       138          Debris
136       139         Illness
137       140       Undertray
138       141  Cooling system

[139 rows x 2 columns]

# Analisis

Comenzamos filtrando las carreras que fueron finalizadas para poder tomar de referencia esto ya que una carrera sin finalizar apareceria como un dato atipico severo y no mostraria nada para nuestro analisis

In [96]:
carreras_finalizadas = results[results['statusId'] ==1]
carreras_finalizadas

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
20320,20323,337,4,6,8,3,1,1,1,25.0,49,1:39:20.396,5960396,45,1,1:58.287,191.706,1
20321,20324,337,13,6,7,2,2,2,2,18.0,49,+16.099,5976495,38,5,1:59.732,189.392,1
20322,20325,337,1,1,2,4,3,3,3,15.0,49,+23.182,5983578,42,4,1:59.560,189.665,1
20323,20326,337,20,9,5,1,4,4,4,12.0,49,+38.799,5999195,32,12,2:00.218,188.627,1
20324,20327,337,3,131,4,5,5,5,5,10.0,49,+40.213,6000609,45,13,2:00.236,188.599,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26744,26750,1144,830,9,1,4,6,6,6,8.0,58,+49.847,5243138,56,6,1:27.765,216.619,1
26745,26751,1144,842,214,10,5,7,7,7,6.0,58,+1:12.560,5265851,30,16,1:29.251,213.012,1
26746,26752,1144,807,210,27,7,8,8,8,4.0,58,+1:15.554,5268845,17,14,1:29.152,213.249,1
26747,26753,1144,4,117,14,8,9,9,9,2.0,58,+1:22.373,5275664,51,7,1:27.948,216.168,1
26748,26754,1144,857,1,81,2,10,10,10,1.0,58,+1:23.821,5277112,51,4,1:27.690,216.804,1

In [99]:
print(f'La nueva tabla carreras_finalizadas tiene {carreras_finalizadas.shape[0]} y {carreras_finalizadas.shape[1]} columnas')
print(f'Mientras que results tenia {results.shape[0]} filas y {results.shape[1]} columnas')
print(f'Vemos entonces que de los resultados totales, {results.shape[0] - carreras_finalizadas.shape[0]} no fueron finalizadas')

La nueva tabla carreras_finalizadas tiene 3305 y 18 columnas
Mientras que results tenia 6436 filas y 18 columnas
Vemos entonces que de los resultados totales, 3131 no fueron finalizadas

A partir de estos datos podriamos analizar que conductores y que escuderias logran finalizar mas carreras.