<a href="https://colab.research.google.com/github/Joaquin-Lobato-Adinolfi/TP_LMC_F1_Analysis/blob/main/TP_LMC_F1_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importacion de librerias y dataset

In [198]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**Ahora, importamos el dataset completo desde la pagina, con el formato que nos dan**

Observese, path funcionara para traer y luego leer los csv que contiene la descarga

In [199]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("rohanrao/formula-1-world-championship-1950-2020")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'formula-1-world-championship-1950-2020' dataset.
Path to dataset files: /kaggle/input/formula-1-world-championship-1950-2020

El dataset contiene muchos csv pero seleccionaremos los necesarios para cumplir con nuestro cometido, necesitando tambien filtrarlos por años principalmente. Para ello, leeremos primero el csv completo y luego dejaremos uno filtrado con los datos necesitados.

**--------------------------------------------------------------------------------------------------------------------------------**

# Dataset

**--------------------------------------------------------------------------------------------------------------------------------**

## Races

In [200]:
# Todas las carreras
races_all = pd.read_csv(path + "/races.csv")
races_all

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,1140,2024,20,32,Mexico City Grand Prix,2024-10-27,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,2024-10-25,22:00:00,2024-10-26,17:30:00,2024-10-26,21:00:00,\N,\N
1121,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,2024-11-01,18:30:00,\N,\N,2024-11-02,18:00:00,2024-11-02,14:00:00
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,2024-11-21,06:00:00,2024-11-22,02:30:00,2024-11-22,06:00:00,\N,\N
1123,1143,2024,23,78,Qatar Grand Prix,2024-12-01,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,2024-11-29,17:30:00,\N,\N,2024-11-30,17:00:00,2024-11-30,13:00:00
1124,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,2024-12-06,13:00:00,2024-12-07,10:30:00,2024-12-07,14:00:00,\N,\N

In [201]:
# Las carreras de 2010 a 2024
races = races_all[races_all["year"] >= 2010]
races

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
336,337,2010,1,3,Bahrain Grand Prix,2010-03-14,12:00:00,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
337,338,2010,2,1,Australian Grand Prix,2010-03-28,06:00:00,http://en.wikipedia.org/wiki/2010_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
338,339,2010,3,2,Malaysian Grand Prix,2010-04-04,08:00:00,http://en.wikipedia.org/wiki/2010_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
339,340,2010,4,17,Chinese Grand Prix,2010-04-18,06:00:00,http://en.wikipedia.org/wiki/2010_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
340,341,2010,5,4,Spanish Grand Prix,2010-05-09,12:00:00,http://en.wikipedia.org/wiki/2010_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,1140,2024,20,32,Mexico City Grand Prix,2024-10-27,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,2024-10-25,22:00:00,2024-10-26,17:30:00,2024-10-26,21:00:00,\N,\N
1121,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,2024-11-01,18:30:00,\N,\N,2024-11-02,18:00:00,2024-11-02,14:00:00
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,2024-11-21,06:00:00,2024-11-22,02:30:00,2024-11-22,06:00:00,\N,\N
1123,1143,2024,23,78,Qatar Grand Prix,2024-12-01,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,2024-11-29,17:30:00,\N,\N,2024-11-30,17:00:00,2024-11-30,13:00:00
1124,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,2024-12-06,13:00:00,2024-12-07,10:30:00,2024-12-07,14:00:00,\N,\N

Procedemos a un analisis de las tablas obtenidas, tanto para un analisis preliminar, como para luego decidir que datos utilizar para nuestra busqueda

In [202]:
races.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
336,337,2010,1,3,Bahrain Grand Prix,2010-03-14,12:00:00,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
337,338,2010,2,1,Australian Grand Prix,2010-03-28,06:00:00,http://en.wikipedia.org/wiki/2010_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
338,339,2010,3,2,Malaysian Grand Prix,2010-04-04,08:00:00,http://en.wikipedia.org/wiki/2010_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
339,340,2010,4,17,Chinese Grand Prix,2010-04-18,06:00:00,http://en.wikipedia.org/wiki/2010_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
340,341,2010,5,4,Spanish Grand Prix,2010-05-09,12:00:00,http://en.wikipedia.org/wiki/2010_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [203]:
races.tail()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
1120,1140,2024,20,32,Mexico City Grand Prix,2024-10-27,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,2024-10-25,22:00:00,2024-10-26,17:30:00,2024-10-26,21:00:00,\N,\N
1121,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,2024-11-01,18:30:00,\N,\N,2024-11-02,18:00:00,2024-11-02,14:00:00
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,2024-11-21,06:00:00,2024-11-22,02:30:00,2024-11-22,06:00:00,\N,\N
1123,1143,2024,23,78,Qatar Grand Prix,2024-12-01,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,2024-11-29,17:30:00,\N,\N,2024-11-30,17:00:00,2024-11-30,13:00:00
1124,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,2024-12-06,13:00:00,2024-12-07,10:30:00,2024-12-07,14:00:00,\N,\N

In [204]:
#Dimensiones
print(f"La tabla races tiene {races.shape[0]} filas y {races.shape[1]} columnas")

La tabla races tiene 305 filas y 18 columnas

In [205]:
races.info()

<class 'pandas.core.frame.DataFrame'>
Index: 305 entries, 336 to 1124
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   raceId       305 non-null    int64
 1   year         305 non-null    int64
 2   round        305 non-null    int64
 3   circuitId    305 non-null    int64
 4   name         305 non-null    object
 5   date         305 non-null    object
 6   time         305 non-null    object
 7   url          305 non-null    object
 8   fp1_date     305 non-null    object
 9   fp1_time     305 non-null    object
 10  fp2_date     305 non-null    object
 11  fp2_time     305 non-null    object
 12  fp3_date     305 non-null    object
 13  fp3_time     305 non-null    object
 14  quali_date   305 non-null    object
 15  quali_time   305 non-null    object
 16  sprint_date  305 non-null    object
 17  sprint_time  305 non-null    object
dtypes: int64(4), object(14)
memory usage: 53.4+ KB

In [206]:
races.dtypes

raceId          int64
year            int64
round           int64
circuitId       int64
name           object
date           object
time           object
url            object
fp1_date       object
fp1_time       object
fp2_date       object
fp2_time       object
fp3_date       object
fp3_time       object
quali_date     object
quali_time     object
sprint_date    object
sprint_time    object
dtype: object

In [207]:
races.isnull().sum()

raceId         0
year           0
round          0
circuitId      0
name           0
date           0
time           0
url            0
fp1_date       0
fp1_time       0
fp2_date       0
fp2_time       0
fp3_date       0
fp3_time       0
quali_date     0
quali_time     0
sprint_date    0
sprint_time    0
dtype: int64

In [208]:
races.describe().round(0)

       raceId    year  round  circuitId
count   305.0   305.0  305.0      305.0
mean    953.0  2017.0   11.0       25.0
std     179.0     4.0    6.0       25.0
min     337.0  2010.0    1.0        1.0
25%     899.0  2013.0    6.0        7.0
50%     985.0  2017.0   11.0       15.0
75%    1064.0  2021.0   16.0       32.0
max    1144.0  2024.0   24.0       80.0

Conclusiones del analisis:

No se encontraron nulls, por lo que la tabla se encuentra completa. El describe no nos arroja datos importantes ya que realiza los analisis sobre int64, siendo estos solo de index o años, valores cuyas medidas estadisticas no son de uso en este analisis. Los otros datos son del tipo object, por eso no se les realiza un analisis estadistico con describe. Mas adelante, llegado el caso de necesitar hacer analisis sobre ellos, veremos la manera de cambiar su tipo de dato o aislar el dato necesario del mismo

**--------------------------------------------------------------------------------------------------------------------------------**

## Results

In [209]:
# Todos los resultados
results_all = pd.read_csv(path + "/results.csv")
results_all

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,26760,1144,825,210,20,14,16,16,16,0.0,57,\N,\N,57,1,1:25.637,222.002,11
26755,26761,1144,859,215,30,12,17,17,17,0.0,55,\N,\N,52,12,1:28.751,214.212,5
26756,26762,1144,822,15,77,9,\N,R,18,0.0,30,\N,\N,14,19,1:29.482,212.462,130
26757,26763,1144,861,3,43,20,\N,R,19,0.0,26,\N,\N,5,17,1:29.411,212.631,5
26758,26764,1144,815,9,11,10,\N,R,20,0.0,0,\N,\N,\N,0,\N,\N,4

In [210]:
# Los resultados de las carreras de 2010 a 2024
results = results_all[results_all['raceId'].isin(races['raceId'])]
results

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
20320,20323,337,4,6,8,3,1,1,1,25.0,49,1:39:20.396,5960396,45,1,1:58.287,191.706,1
20321,20324,337,13,6,7,2,2,2,2,18.0,49,+16.099,5976495,38,5,1:59.732,189.392,1
20322,20325,337,1,1,2,4,3,3,3,15.0,49,+23.182,5983578,42,4,1:59.560,189.665,1
20323,20326,337,20,9,5,1,4,4,4,12.0,49,+38.799,5999195,32,12,2:00.218,188.627,1
20324,20327,337,3,131,4,5,5,5,5,10.0,49,+40.213,6000609,45,13,2:00.236,188.599,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,26760,1144,825,210,20,14,16,16,16,0.0,57,\N,\N,57,1,1:25.637,222.002,11
26755,26761,1144,859,215,30,12,17,17,17,0.0,55,\N,\N,52,12,1:28.751,214.212,5
26756,26762,1144,822,15,77,9,\N,R,18,0.0,30,\N,\N,14,19,1:29.482,212.462,130
26757,26763,1144,861,3,43,20,\N,R,19,0.0,26,\N,\N,5,17,1:29.411,212.631,5
26758,26764,1144,815,9,11,10,\N,R,20,0.0,0,\N,\N,\N,0,\N,\N,4

Procedemos a un analisis de las tablas obtenidas, tanto para un analisis preliminar, como para luego decidir que datos utilizar para nuestra busqueda

In [211]:
results.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
20320,20323,337,4,6,8,3,1,1,1,25.0,49,1:39:20.396,5960396,45,1,1:58.287,191.706,1
20321,20324,337,13,6,7,2,2,2,2,18.0,49,+16.099,5976495,38,5,1:59.732,189.392,1
20322,20325,337,1,1,2,4,3,3,3,15.0,49,+23.182,5983578,42,4,1:59.560,189.665,1
20323,20326,337,20,9,5,1,4,4,4,12.0,49,+38.799,5999195,32,12,2:00.218,188.627,1
20324,20327,337,3,131,4,5,5,5,5,10.0,49,+40.213,6000609,45,13,2:00.236,188.599,1

In [212]:
results.tail()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
26754,26760,1144,825,210,20,14,16,16,16,0.0,57,\N,\N,57,1,1:25.637,222.002,11
26755,26761,1144,859,215,30,12,17,17,17,0.0,55,\N,\N,52,12,1:28.751,214.212,5
26756,26762,1144,822,15,77,9,\N,R,18,0.0,30,\N,\N,14,19,1:29.482,212.462,130
26757,26763,1144,861,3,43,20,\N,R,19,0.0,26,\N,\N,5,17,1:29.411,212.631,5
26758,26764,1144,815,9,11,10,\N,R,20,0.0,0,\N,\N,\N,0,\N,\N,4

In [213]:
#Dimensiones
print(f"La tabla results tiene {results.shape[0]} filas y {results.shape[1]} columnas")

La tabla results tiene 6436 filas y 18 columnas

In [214]:
results.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6436 entries, 20320 to 26758
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         6436 non-null   int64
 1   raceId           6436 non-null   int64
 2   driverId         6436 non-null   int64
 3   constructorId    6436 non-null   int64
 4   number           6436 non-null   object
 5   grid             6436 non-null   int64
 6   position         6436 non-null   object
 7   positionText     6436 non-null   object
 8   positionOrder    6436 non-null   int64
 9   points           6436 non-null   float64
 10  laps             6436 non-null   int64
 11  time             6436 non-null   object
 12  milliseconds     6436 non-null   object
 13  fastestLap       6436 non-null   object
 14  rank             6436 non-null   object
 15  fastestLapTime   6436 non-null   object
 16  fastestLapSpeed  6436 non-null   object
 17  statusId         6436 non-null   int64
dtypes: float64(1), int64(8), object(9)
memory usage: 955.3+ KB

In [215]:
results.dtypes

resultId             int64
raceId               int64
driverId             int64
constructorId        int64
number              object
grid                 int64
position            object
positionText        object
positionOrder        int64
points             float64
laps                 int64
time                object
milliseconds        object
fastestLap          object
rank                object
fastestLapTime      object
fastestLapSpeed     object
statusId             int64
dtype: object

In [216]:
results.isnull().sum()

resultId           0
raceId             0
driverId           0
constructorId      0
number             0
grid               0
position           0
positionText       0
positionOrder      0
points             0
laps               0
time               0
milliseconds       0
fastestLap         0
rank               0
fastestLapTime     0
fastestLapSpeed    0
statusId           0
dtype: int64

In [217]:
results.describe().round(2)

,resultId,raceId,driverId,constructorId,grid,positionOrder,points,laps,statusId
count,6436.00,6436.00,6436.00,6436.00,6436.00,6436.00,6436.00,6436.00,6436.00
mean,23543.37,942.87,538.66,71.01,10.87,11.11,4.81,53.26,9.34
std,1860.50,186.14,386.44,85.71,6.24,6.20,7.14,17.86,20.00
min,20323.00,337.00,1.00,1.00,0.00,1.00,0.00,0.00,1.00
25%,21931.75,890.00,20.00,5.00,6.00,6.00,0.00,51.00,1.00
50%,23542.50,977.00,817.00,10.00,11.00,11.00,0.00,56.00,1.00
75%,25155.25,1060.00,835.00,131.00,16.00,16.00,8.00,66.00,11.00
max,26764.00,1144.00,862.00,215.00,24.00,24.00,50.00,87.00,141.00

Conclusiones del analisis:

Si bien no se muestran nulls, es de notar que hay valores marcados con "\N". Esto muestra o que no hay datos o que no han sido tomados. Nos iclinamamos a que no han sido tomados ya que, mas adelante, nos sera mas util analizar solo los datos de corredores que hayan finalizado la carrera (status = 1) y en los casos que figuran con "\N" se puede ver que el status no es ese, denotando una no finalizacion de carrera.

**--------------------------------------------------------------------------------------------------------------------------------**

## Drivers

In [218]:
# Todos los corredores
drivers_all = pd.read_csv(path + "/drivers.csv")
drivers_all

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,30,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,38,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto
860,862,doohan,61,DOO,Jack,Doohan,2003-01-20,Australian,http://en.wikipedia.org/wiki/Jack_Doohan

In [219]:
# Los corredores de las carreras filtradas
drivers = drivers_all[drivers_all['driverId'].isin(results['driverId'])]
drivers

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,30,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,38,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto
860,862,doohan,61,DOO,Jack,Doohan,2003-01-20,Australian,http://en.wikipedia.org/wiki/Jack_Doohan

Procedemos a un analisis de las tablas obtenidas, tanto para un analisis preliminar, como para luego decidir que datos utilizar para nuestra busqueda

In [220]:
drivers.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [221]:
drivers.tail()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,30,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,38,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto
860,862,doohan,61,DOO,Jack,Doohan,2003-01-20,Australian,http://en.wikipedia.org/wiki/Jack_Doohan

In [222]:
#Dimensiones
print(f"La tabla results tiene {drivers.shape[0]} filas y {drivers.shape[1]} columnas")

La tabla results tiene 80 filas y 9 columnas

In [223]:
drivers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 80 entries, 0 to 860
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driverId     80 non-null     int64
 1   driverRef    80 non-null     object
 2   number       80 non-null     object
 3   code         80 non-null     object
 4   forename     80 non-null     object
 5   surname      80 non-null     object
 6   dob          80 non-null     object
 7   nationality  80 non-null     object
 8   url          80 non-null     object
dtypes: int64(1), object(8)
memory usage: 8.3+ KB

In [224]:
drivers.dtypes

driverId        int64
driverRef      object
number         object
code           object
forename       object
surname        object
dob            object
nationality    object
url            object
dtype: object

In [225]:
drivers.isnull().sum()

driverId       0
driverRef      0
number         0
code           0
forename       0
surname        0
dob            0
nationality    0
url            0
dtype: int64

In [226]:
drivers.describe()

         driverId
count   80.000000
mean   585.075000
std    374.120057
min      1.000000
25%     38.500000
50%    822.500000
75%    842.250000
max    862.000000

Conlusiones del analisis:

Nada notable, el describe no muestra nada. Los datos seran utiles para saber exactamente de que corredor hablamos cuando utilizamos sus datos.

**--------------------------------------------------------------------------------------------------------------------------------**

## Contructors

In [227]:
# Todas las escuderias
constructors_all = pd.read_csv(path + "/constructors.csv")
constructors_all

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
...,...,...,...,...,...
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
208,211,racing_point,Racing Point,British,http://en.wikipedia.org/wiki/Racing_Point_F1_Team
209,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
210,214,alpine,Alpine F1 Team,French,http://en.wikipedia.org/wiki/Alpine_F1_Team
211,215,rb,RB F1 Team,Italian,http://en.wikipedia.org/wiki/RB_Formula_One_Team

In [228]:
# Las escuderias de 2010 a 2024
constructors = constructors_all[constructors_all['constructorId'].isin(results['constructorId'])]
constructors

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
5,6,ferrari,Ferrari,Italian,http://en.wikipedia.org/wiki/Scuderia_Ferrari
8,9,red_bull,Red Bull,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing
9,10,force_india,Force India,Indian,http://en.wikipedia.org/wiki/Racing_Point_Forc...
14,15,sauber,Sauber,Swiss,http://en.wikipedia.org/wiki/Sauber_Motorsport
49,51,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...
115,117,aston_martin,Aston Martin,British,http://en.wikipedia.org/wiki/Aston_Martin_in_F...
129,131,mercedes,Mercedes,German,http://en.wikipedia.org/wiki/Mercedes-Benz_in_...
162,164,hrt,HRT,Spanish,http://en.wikipedia.org/wiki/Hispania_Racing
164,166,virgin,Virgin,British,http://en.wikipedia.org/wiki/Virgin_Racing
202,205,lotus_racing,Lotus,Malaysian,http://en.wikipedia.org/wiki/Lotus_Racing
203,206,marussia,Marussia,Russian,http://en.wikipedia.org/wiki/Marussia_F1
204,207,caterham,Caterham,Malaysian,http://en.wikipedia.org/wiki/Caterham_F1
205,208,lotus_f1,Lotus F1,British,http://en.wikipedia.org/wiki/Lotus_F1
206,209,manor,Manor Marussia,British,http://en.wikipedia.org/wiki/Manor_Motorsport
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
208,211,racing_point,Racing Point,British,http://en.wikipedia.org/wiki/Racing_Point_F1_Team
209,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
210,214,alpine,Alpine F1 Team,French,http://en.wikipedia.org/wiki/Alpine_F1_Team
211,215,rb,RB F1 Team,Italian,http://en.wikipedia.org/wiki/RB_Formula_One_Team

Procedemos a un analisis de las tablas obtenidas, tanto para un analisis preliminar, como para luego decidir que datos utilizar para nuestra busqueda

In [229]:
constructors.head()

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
5,6,ferrari,Ferrari,Italian,http://en.wikipedia.org/wiki/Scuderia_Ferrari

In [230]:
constructors.tail()

,constructorId,constructorRef,name,nationality,url
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
208,211,racing_point,Racing Point,British,http://en.wikipedia.org/wiki/Racing_Point_F1_Team
209,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
210,214,alpine,Alpine F1 Team,French,http://en.wikipedia.org/wiki/Alpine_F1_Team
211,215,rb,RB F1 Team,Italian,http://en.wikipedia.org/wiki/RB_Formula_One_Team

In [231]:
#Dimensiones
print(f"La tabla results tiene {constructors.shape[0]} filas y {constructors.shape[1]} columnas")

La tabla results tiene 23 filas y 5 columnas

In [232]:
constructors.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, 0 to 211
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   constructorId   23 non-null     int64
 1   constructorRef  23 non-null     object
 2   name            23 non-null     object
 3   nationality     23 non-null     object
 4   url             23 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.1+ KB

In [233]:
constructors.dtypes

constructorId      int64
constructorRef    object
name              object
nationality       object
url               object
dtype: object

In [234]:
constructors.isnull().sum()

constructorId     0
constructorRef    0
name              0
nationality       0
url               0
dtype: int64

In [235]:
constructors.describe()

       constructorId
count      23.000000
mean      120.869565
std        93.576563
min         1.000000
25%         9.500000
50%       164.000000
75%       208.500000
max       215.000000

Conclusiones del analisis:

Al igual que drivers, los datos se utilizaran para emparejar datos con escuderias luego

**--------------------------------------------------------------------------------------------------------------------------------**

## Qualifying

In [236]:
# Todas las qualis
qualifying_all = pd.read_csv(path + "/qualifying.csv")
qualifying_all

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236
...,...,...,...,...,...,...,...,...,...
10489,10547,1144,848,3,23,16,1:23.821,\N,\N
10490,10548,1144,855,15,24,17,1:23.880,\N,\N
10491,10549,1144,1,131,44,18,1:23.887,\N,\N
10492,10550,1144,861,3,43,19,1:23.912,\N,\N
10493,10551,1144,862,214,61,20,1:24.105,\N,\N

In [237]:
# Las qualis de 2010 a 2024
qualifying = qualifying_all[qualifying_all['raceId'].isin(races['raceId'])]
qualifying

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
3324,3326,337,20,9,5,1,1:55.029,1:53.883,1:54.101
3325,3327,337,13,6,7,2,1:55.313,1:54.331,1:54.242
3326,3328,337,4,6,8,3,1:54.612,1:54.172,1:54.608
3327,3329,337,1,1,2,4,1:55.341,1:54.707,1:55.217
3328,3330,337,3,131,4,5,1:55.463,1:54.682,1:55.241
...,...,...,...,...,...,...,...,...,...
10489,10547,1144,848,3,23,16,1:23.821,\N,\N
10490,10548,1144,855,15,24,17,1:23.880,\N,\N
10491,10549,1144,1,131,44,18,1:23.887,\N,\N
10492,10550,1144,861,3,43,19,1:23.912,\N,\N
10493,10551,1144,862,214,61,20,1:24.105,\N,\N

Procedemos a un analisis de las tablas obtenidas, tanto para un analisis preliminar, como para luego decidir que datos utilizar para nuestra busqueda

In [238]:
qualifying.head()

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
3324,3326,337,20,9,5,1,1:55.029,1:53.883,1:54.101
3325,3327,337,13,6,7,2,1:55.313,1:54.331,1:54.242
3326,3328,337,4,6,8,3,1:54.612,1:54.172,1:54.608
3327,3329,337,1,1,2,4,1:55.341,1:54.707,1:55.217
3328,3330,337,3,131,4,5,1:55.463,1:54.682,1:55.241

In [239]:
qualifying.tail()

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
10489,10547,1144,848,3,23,16,1:23.821,\N,\N
10490,10548,1144,855,15,24,17,1:23.880,\N,\N
10491,10549,1144,1,131,44,18,1:23.887,\N,\N
10492,10550,1144,861,3,43,19,1:23.912,\N,\N
10493,10551,1144,862,214,61,20,1:24.105,\N,\N

In [240]:
#Dimensiones
print(f"La tabla results tiene {qualifying.shape[0]} filas y {qualifying.shape[1]} columnas")

La tabla results tiene 6412 filas y 9 columnas

In [241]:
qualifying.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6412 entries, 3324 to 10493
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   qualifyId      6412 non-null   int64
 1   raceId         6412 non-null   int64
 2   driverId       6412 non-null   int64
 3   constructorId  6412 non-null   int64
 4   number         6412 non-null   int64
 5   position       6412 non-null   int64
 6   q1             6412 non-null   object
 7   q2             6390 non-null   object
 8   q3             6366 non-null   object
dtypes: int64(6), object(3)
memory usage: 500.9+ KB

In [242]:
qualifying.dtypes

qualifyId         int64
raceId            int64
driverId          int64
constructorId     int64
number            int64
position          int64
q1               object
q2               object
q3               object
dtype: object

In [243]:
qualifying.isnull().sum()

qualifyId         0
raceId            0
driverId          0
constructorId     0
number            0
position          0
q1                0
q2               22
q3               46
dtype: int64

In [244]:
qualifying.describe().round(2)

       qualifyId   raceId  driverId  constructorId   number  position
count    6412.00  6412.00   6412.00        6412.00  6412.00   6412.00
mean     7256.98   942.93    538.81          71.07    22.89     11.07
std      1965.43   186.45    386.40          85.72    21.85      6.17
min      3326.00   337.00      1.00           1.00     1.00      1.00
25%      5684.75   890.00     20.00           5.00     8.00      6.00
50%      7308.50   977.00    817.00          10.00    17.00     11.00
75%      8929.25  1060.00    835.00         131.00    27.00     16.00
max     10551.00  1144.00    862.00         215.00    99.00     24.00

Conclusiones del analisis:

Es de notar en este caso la aparicion de nulls en los datos. Puede deberse a retiros previos a las q2 y/o q3 de algun corredor, cosa que podemos corroborar luego cuando chequeemos carreras y qualis finalizadas.

**--------------------------------------------------------------------------------------------------------------------------------**

## Status

(Dato para filtrar excepciones)

In [245]:
status = pd.read_csv(path + "/status.csv")
with pd.option_context("display.max_rows", None):
    display(status)

     statusId              status
0           1            Finished
1           2        Disqualified
2           3            Accident
3           4           Collision
4           5              Engine
5           6             Gearbox
6           7        Transmission
7           8              Clutch
8           9          Hydraulics
9          10          Electrical
10         11              +1 Lap
11         12             +2 Laps
12         13             +3 Laps
13         14             +4 Laps
14         15             +5 Laps
15         16             +6 Laps
16         17             +7 Laps
17         18             +8 Laps
18         19             +9 Laps
19         20            Spun off
20         21            Radiator
21         22          Suspension
22         23              Brakes
23         24        Differential
24         25         Overheating
25         26          Mechanical
26         27                Tyre
27         28         Driver Seat
28         29            Puncture
29         30          Driveshaft
30         31             Retired
31         32       Fuel pressure
32         33          Front wing
33         34      Water pressure
34         35          Refuelling
35         36               Wheel
36         37            Throttle
37         38            Steering
38         39           Technical
39         40         Electronics
40         41         Broken wing
41         42    Heat shield fire
42         43             Exhaust
43         44            Oil leak
44         45            +11 Laps
45         46           Wheel rim
46         47          Water leak
47         48           Fuel pump
48         49           Track rod
49         50            +17 Laps
50         51        Oil pressure
51        128            +42 Laps
52         53            +13 Laps
53         54            Withdrew
54         55            +12 Laps
55         56         Engine fire
56        129      Engine misfire
57         58            +26 Laps
58         59       Tyre puncture
59         60         Out of fuel
60         61           Wheel nut
61         62      Not classified
62         63          Pneumatics
63         64            Handling
64         65           Rear wing
65         66                Fire
66         67       Wheel bearing
67         68            Physical
68         69         Fuel system
69         70            Oil line
70         71            Fuel rig
71         72      Launch control
72         73             Injured
73         74                Fuel
74         75          Power loss
75         76          Vibrations
76         77           107% Rule
77         78              Safety
78         79          Drivetrain
79         80            Ignition
80         81     Did not qualify
81         82              Injury
82         83             Chassis
83         84             Battery
84         85             Stalled
85         86           Halfshaft
86         87          Crankshaft
87         88            +10 Laps
88         89     Safety concerns
89         90       Not restarted
90         91          Alternator
91         92         Underweight
92         93         Safety belt
93         94            Oil pump
94         95           Fuel leak
95         96            Excluded
96         97  Did not prequalify
97         98           Injection
98         99         Distributor
99        100       Driver unwell
100       101               Turbo
101       102            CV joint
102       103          Water pump
103       104      Fatal accident
104       105         Spark plugs
105       106           Fuel pipe
106       107          Eye injury
107       108            Oil pipe
108       109                Axle
109       110          Water pipe
110       111            +14 Laps
111       112            +15 Laps
112       113            +25 Laps
113       114            +18 Laps
114       115            +22 Laps
115       116            +16 Laps
116       117            +24 Laps
117       118            +29 Laps
118       119            +23 Laps
119       120            +21 Laps
120       121             Magneto
121       122            +44 Laps
122       123            +30 Laps
123       124            +19 Laps
124       125            +46 Laps
125       126        Supercharger
126       127            +20 Laps
127       130    Collision damage
128       131          Power Unit
129       132                 ERS
130       133            +49 Laps
131       134            +38 Laps
132       135          Brake duct
133       136                Seat
134       137              Damage
135       138              Debris
136       139             Illness
137       140           Undertray
138       141      Cooling system

# Pregunta de Investigacion

**a)** ¿Qué pesa más en el resultado de una carrera de Fórmula 1 (2010–2024): el rendimiento del auto o el talento del piloto?

Para ellos no solo analizaremos los resultados de cada piloto, sino que comparar las escuderias una con otra como tambien los pilotos con su compañero de equipo

**b)** La motivacion se gesta no solo de la incognita de responder la pregunta en si, que ya arroja de por si datos utiles, sino que ayudaria, en un hipotetico, a poder decidir donde debe una escuderia focalizar e invertir para tener un mayor impacto en las carreras. Esto es, si debe poner mas foco en el auto o si debe capacitar o buscar mejores corredores.

**c)** (Conclusion para luego del analisis)

# Preanalisis

Prompts a Claude:



*   A partir de los datos y la pregunta de hipotesis, ayudanos a decidir que variables podemos utilizar para el analisis planteado. Focaliza en las diferencias auto a auto y compañero a compañero.
*   Con toda esta informacion, quiero armar una hoja de ruta de como encarar el analisis para que sea mas comprensivo. Para ello, recomendame que me convendria filtrar y encarar el analisis pero sin decirme como hacerlo

A partir de las respuestas de Claude y nuestra vision para el proyecto, es necesario para el analisis sentar bases de como se realizara.

Definimos primero a que nos referimos con auto y talento del piloto. Siendo que tomamos un rango de tiempo significativamente amplio, en terminos de avances tecnologicos de la F1, definiremos "auto" o "resultados de auto" como la performance de la escuderia durante estos años analizados. Esto entonces compete a, indistintamente de los corredores, como finalizo cada escuderia las carreras, un promedio de finalizaciones por carrera, tiempos, posiciones y puntos. Con esta informacion podremos, aisladamente, comparar auto a auto, esto es, cuales tienen mejores resultados unos con otros.

En cuanto a talento, aqui observaremos los resultados de los corredores por si solos, indistintamente de sus autos y compañeros.

En base a estos datos, podremos entonces confeccionar un analisis combinando ambas partes de distintas maneras, ahora si analizando la performace entre compañeros con mismo auto, como se refleja un cambio de escuderia o compañero y plantear una forma de comparar performances de correredores de distintas escuderias donde objetivamente se analice cual es "mas talentoso". Esto seria, por ejemplo, cual obtiene mejor promedio considerando el "valor" de su auto comparado con los otros.

Sentadas las bases necesarias reconoceremos que el analisis puede realizarse de forma mas exhaustiva, pero, para lo pedido en la rubrica, consideramos que la informacion, datos y conclusiones seran mas que cumplidoras.

Procedemos entonces a una hoja de ruta del analisis:

*   Filtracion de datos: Buscaremos las carreras finalizadas indistintamente de corredor/auto. A partir de esta, filtraremos por escuderia y corredor para tener ya informacion util. Asimismo, transformaremos datos para utilizacion (varios de los datos de medidas numericas son objetos). (graficos?)
*   Comparaciones: A partir de los filtros se realizaran las comparaciones compañero a compañero y auto a auto, para luego mezclar estas para sacar las conclusiones necesarias.


*   Graficos y analisis de los mismos

# Analisis

## Filtro de datos

Comenzamos filtrando las carreras que fueron finalizadas para poder tomar de referencia esto ya que una carrera sin finalizar apareceria como un dato atipico severo y no mostraria nada para nuestro analisis.

Con ayuda de Claude, que observo en el notebook, vimos que con solo el status ID de 1 para finished no representaba realmente cuantos terminaban, sino que los lapped, osea, cualquier corredor cuyo status es "+ 'alguna/s vueltas'" tambien cuentan como finalizados. Lo arreglamos y tenemos muchos mas datos con los que trabajar.

In [246]:
status_finalizados = status[status["status"].str.startswith("+") | (status['status'] == "Finished")]
carreras_finalizadas = results[results['statusId'].isin(status_finalizados['statusId'])].reset_index()
carreras_finalizadas

,index,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,20320,20323,337,4,6,8,3,1,1,1,25.0,49,1:39:20.396,5960396,45,1,1:58.287,191.706,1
1,20321,20324,337,13,6,7,2,2,2,2,18.0,49,+16.099,5976495,38,5,1:59.732,189.392,1
2,20322,20325,337,1,1,2,4,3,3,3,15.0,49,+23.182,5983578,42,4,1:59.560,189.665,1
3,20323,20326,337,20,9,5,1,4,4,4,12.0,49,+38.799,5999195,32,12,2:00.218,188.627,1
4,20324,20327,337,3,131,4,5,5,5,5,10.0,49,+40.213,6000609,45,13,2:00.236,188.599,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5275,26750,26756,1144,852,215,22,11,12,12,12,0.0,57,\N,\N,41,15,1:29.200,213.134,11
5276,26751,26757,1144,855,15,24,15,13,13,13,0.0,57,\N,\N,56,8,1:27.982,216.085,11
5277,26752,26758,1144,840,117,18,13,14,14,14,0.0,57,\N,\N,42,11,1:28.604,214.568,11
5278,26753,26759,1144,862,214,61,17,15,15,15,0.0,57,\N,\N,56,13,1:29.121,213.323,11
5279,26754,26760,1144,825,210,20,14,16,16,16,0.0,57,\N,\N,57,1,1:25.637,222.002,11

Reafirmamos la anterior busqueda de datos, dando con lo necesario para continuar el analisis

In [247]:
print(f'La nueva tabla carreras_finalizadas tiene {carreras_finalizadas.shape[0]} y {carreras_finalizadas.shape[1]} columnas')
print(f'Mientras que results tenia {results.shape[0]} filas y {results.shape[1]} columnas')
print(f'Vemos entonces que de los resultados totales, {results.shape[0] - carreras_finalizadas.shape[0]} conductores no finalizaron la carrera por alguna razon')

La nueva tabla carreras_finalizadas tiene 5280 y 19 columnas
Mientras que results tenia 6436 filas y 18 columnas
Vemos entonces que de los resultados totales, 1156 conductores no finalizaron la carrera por alguna razon

Ahora, un pequeño paso intermedio, pero esclarecedor, es ver con cuantas carreras, corredores y escuderias estamos trabajando. Estos datos, ademas de aportarnos informacion necesaria, nos ayudaran a atajar errores del tipo: considerar ids en vez de las carreras en si, dividir por mas correrdores de los que hay o considerar a una escuderia mas de una vez ya que dos corredores forman parte de ella.

In [248]:
print(f"Carreras totales analizadas:", carreras_finalizadas['raceId'].nunique())
print(f"Corredores totales analizados:", carreras_finalizadas['driverId'].nunique())
print(f"Escuderias totales analizadas:", carreras_finalizadas['constructorId'].nunique())

Carreras totales analizadas: 305
Corredores totales analizados: 79
Escuderias totales analizadas: 23

Una decision importante es lo que manejaremos de la tabla qualifying. No nos ayudaria combinarla con la de las carreras en si, por lo que la utilizaremos por su cuenta para hacer un analisis paralelo y luego comparar con la de las carreras. Realizamos un pequeño filtro para analizar si coinciden los numeros de carreras, corredores y escuderias totales.

In [249]:
print(f"Carreras totales analizadas:", qualifying['raceId'].nunique())
print(f"Corredores totales analizados:", qualifying['driverId'].nunique())
print(f"Escuderias totales analizadas:", qualifying['constructorId'].nunique())

Carreras totales analizadas: 305
Corredores totales analizados: 80
Escuderias totales analizadas: 23

Hay un corredor de mas, el cual puede ser un dato atipico para nuestro analisis. Buscaremos quien es.

In [250]:
drivers_quali = qualifying['driverId'].unique()
drivers_quali

array([ 20,  13,   4,   1,   3,  17,  30,  18,   9,  16,  22,  24, 807,
        37,  67, 155, 808, 153,  10,  15,   5, 810, 811, 812,  29,   2,
        32, 815, 814, 813, 816,  39, 817, 154, 818,   8, 819, 822, 821,
       824, 820, 823, 825, 826, 828, 827, 829, 832, 831, 830, 833, 834,
       835, 837, 836, 838, 839, 841, 840, 842, 843, 844, 845, 846, 848,
       847, 849, 851, 850, 852, 854, 853, 855, 856, 858, 857, 859, 860,
       861, 862])

In [251]:
drivers_carrera = carreras_finalizadas['driverId'].unique()
drivers_carrera

array([  4,  13,   1,  20,   3,  30,  18,  17,  24,  22,   9,  16, 153,
       807,   5,  37, 812,  67, 810, 811,  15, 808, 155,  10,  29,   2,
        32, 814, 816,  39, 815, 813, 817,   8, 818, 819, 154, 821, 822,
       824, 820, 823, 825, 826, 828, 829, 831, 832, 830, 833, 834, 835,
       836, 838, 837, 839, 841, 840, 842, 843, 844, 845, 846, 848, 847,
       849, 851, 850, 852, 854, 853, 855, 856, 858, 857, 859, 860, 861,
       862])

In [252]:
def corredor_atipico():
    for i in drivers_quali:
        if i not in drivers_carrera:
            return int(i)

print(corredor_atipico())

827

Pregunte a Claude por validez y me dijo que podria haberse simplificado haciendo **np.setdiff1d(drivers_quali, drivers_carrera)**. Dejo ambas versiones, la mia y la sugerida por Claude para mostrar que son el mismo valor, ayudandome asi a corroborar.

Prompt utlizado: "Sea esta la funcion creada para hallar el valor de driver diferente, ayudame a entender por que es que no me arroja un valor"

In [253]:
def corredor_atipico_version_erronea():
    for i in drivers_quali:
        if i in drivers_carrera:
            return int(i)

print(corredor_atipico_version_erronea) #Version erronea

<function corredor_atipico_version_erronea at 0x7e203d7c7420>

Adjunto funcion original, Claude me hizo notar el cambio de not in en vez de in en el if y que me faltaba el parentesis al pedir el print de la funcion.

In [254]:
valor_atipico = np.setdiff1d(drivers_quali, drivers_carrera)

In [255]:
np.setdiff1d(drivers_carrera, drivers_quali)

array([], dtype=int64)

Chequeamos ambos lados y vemos que el segundo es vacio, lo cual nos confirma que todos los que corrieron tambien estuvieron en la quali

In [256]:
piloto_atipico = drivers[drivers['driverId'].isin(valor_atipico)][["driverId", "forename", "surname"]]
piloto_atipico
#Dato importante: https://es.wikipedia.org/wiki/André_Lotterer. En la seccion de F1 se muestra que corrio solo una vuelta en las qualis y que luego no corrio.
# Confirmamos su ausencia y atipicidad.

     driverId forename   surname
826       827    André  Lotterer

## Tablas

Ahora, con los datos filtrados, definiremos que tablas y datos utilizaremos. Como dicho antes, utilizaremos qualifying y carreras_finalizadas. Aun asi, me gustaria, para ordenar, tener tablas mas completas (driverId y el apellido en conjunto, etc.) para no necesitrar traer tantas tablas.

Para ello, definiremos datos de las tablas a utilizar y dejaremos dos tablas "finales" para el analisis y luego graficos.

Expomdremos la logica de las tablas para luego realizarla:

* Tabla Carreras:
  * Eliminaremos ResultId e Index pues ya no nos haran falta.
  * <mark>Resetearemos el index de raceId para trabajar de forma mas sencilla</mark>
  * Mantendremos driverId y constructorId pero <mark>agregaremos a ambos el "surname" del corredor</mark> y el nombre de la escuderia, sacados de sus respectivas tablas.
  * <mark>Utilizaremos positionOrder pues es el dato que siempre esta, indistintamente de abandono/falla/no presentacion. Para nuestro filtro, estas excepciones las hemos eliminados pero igualmente nos quedaremos con el valor de positionOrder ya que es el que mejor reflejaria la posicion de ser que no hubiesemos filtrado.</mark>
  * Sacaremos number, el numero del auto. No nos ayuda en nuestro analisis.
  * Mantendremos grid pues es la posicion en la que comenzo la carrera y podemos analizar cuantas posiciones perdio o gano, y como se relaciona con las qualis. Notese, grid = 0 existe y es arrancar desde boxes, dato que tendremos en cuenta tambien.
  * Eliminaremos points pues <mark> varia mucho con los años por lo que no nos ayuda para tener datos objetivos.</mark>
  * Mantendremos laps <mark>y statusId para control.</mark>
  * Los datos de tiempo y fastestLaps <mark> son muy subjetivos y cambian mucho con los años. No suelen representar una consistencia ni de piloto ni de escuderia por lo que, para un analisis mas objetivo, no los tomaremos en cuenta.</mark>

* Tabla Qualifying:
  * <mark>Resetearemos raceId para que quede igual a la de carreras.</mark>
  * diverId y constructirId, mismo trato que carreras, agregando los nombres.
  * Sacaremos number
  * <mark>La columna position representa la posicion final o "de salida" para la carrera, sin penalizaciones aplicadas. No siempre es la misma que en carrera, por lo que la mantendremos.</mark>
  * Las tres qualis, las utilizaremos.

Prompt a Claude:

 "Hemos realizado este filtrado para anlisis, toma el rol de un analista de datos senior y juzga el filtrado ayudandonos a ver si hay algo que olvidamos o podriamos sumar"

Nos arrojo bastantes propuestas y cambios. A continuacion realizamos los cambios. Dejamos ambos casos, el primer draft y el filtro final para ver los cambios impactados (maracados con color).

Expomdremos la logica de las tablas para luego realizarla:

* Tabla Carreras:
  * Eliminaremos ResultId e Index pues ya no nos haran falta.
  * <mark>Se mantiene raceId.</mark>
  * Mantendremos driverId y constructorId pero <mark>agregaremos una columna que combine el forename y surname del driver (algunos corredores tienen el mismo surname)</mark>, y el nombre de la escuderia, sacados de sus respectivas tablas.
  * <mark>Utilizaremos positionOrder pues es el dato que esta completo,indistintamente de abandono/falla/no presentacion, a diferencia de position o positionText.</mark>
  * Sacaremos number, el numero del auto. No nos ayuda en nuestro analisis.
  * Mantendremos grid pues es la posicion en la que comenzo la carrera y podemos analizar cuantas posiciones perdio o gano, y como se relaciona con las qualis. Notese, grid = 0 existe y es arrancar desde boxes, dato que tendremos en cuenta tambien para el analisis,<mark> puesto que se veria como que parte antes de todos.</mark>
  * Eliminaremos points pues <mark> su calculo no es lineal e intervendria con el analisis.</mark>
  * Mantendremos laps para control. <mark>Tambien para control, agregaremos el status de statusId, que indica para mejor representacion.</mark>
  * Los datos de tiempo y fastestLaps <mark> estan incompletos y muchas veces no muestran informacion "real" de la carrera. Seran eliminados, no son necesarios para este analisis.</mark>
  * <mark>Agregamos "year" desde races</mark>

* Tabla Qualifying:
  * <mark>Se mantiene raceId</mark>
  * diverId y constructirId, mismo trato que carreras, agregando los nombres.
  * Sacaremos number
  * <mark>La columna position representa la posicion de clasificacion, que luego se puede comparar con grid, que es la de salida y puede variar debido a penalizaciones.</mark>
  * Las tres qualis, las utilizaremos.
  * <mark>Agregamos "year" desde races</mark>

Hay algunas cosas mas que cambian o seran de necesidad aclarar pero lo veremos impactado cuando comenzemos el analisis.

Ahora, realizamos las tablas con lo dicho.

In [257]:
carreras_analisis = carreras_finalizadas[['raceId', 'driverId', 'constructorId', 'grid','positionOrder', 'laps', "statusId"]].copy()

race_year = dict(zip(races["raceId"], races["year"]))

nombre_completo = drivers["forename"] + " " + drivers["surname"]
piloto_por_id = dict(zip(drivers["driverId"], nombre_completo))

escuderia_por_id = dict(zip(constructors["constructorId"], constructors["name"]))

status_por_id = dict(zip(status['statusId'], status['status']))

carreras_analisis.insert(1, "year", carreras_analisis["raceId"].map(race_year))
carreras_analisis.insert(3, "driverName", carreras_analisis["driverId"].map(piloto_por_id))
carreras_analisis.insert(5, "constructorName", carreras_analisis["constructorId"].map(escuderia_por_id))
carreras_analisis.insert(10, "status", carreras_analisis["statusId"].map(status_por_id))

carreras_analisis

,raceId,year,driverId,driverName,constructorId,constructorName,grid,positionOrder,laps,statusId,status
0,337,2010,4,Fernando Alonso,6,Ferrari,3,1,49,1,Finished
1,337,2010,13,Felipe Massa,6,Ferrari,2,2,49,1,Finished
2,337,2010,1,Lewis Hamilton,1,McLaren,4,3,49,1,Finished
3,337,2010,20,Sebastian Vettel,9,Red Bull,1,4,49,1,Finished
4,337,2010,3,Nico Rosberg,131,Mercedes,5,5,49,1,Finished
...,...,...,...,...,...,...,...,...,...,...,...
5275,1144,2024,852,Yuki Tsunoda,215,RB F1 Team,11,12,57,11,+1 Lap
5276,1144,2024,855,Guanyu Zhou,15,Sauber,15,13,57,11,+1 Lap
5277,1144,2024,840,Lance Stroll,117,Aston Martin,13,14,57,11,+1 Lap
5278,1144,2024,862,Jack Doohan,214,Alpine F1 Team,17,15,57,11,+1 Lap
5279,1144,2024,825,Kevin Magnussen,210,Haas F1 Team,14,16,57,11,+1 Lap

Tenemos armada nuestra tabla de carreras para el analisis.

In [258]:
qualifying_analisis = qualifying[['qualifyId', 'raceId', 'driverId',	'constructorId', 'position',	'q1',	'q2',	'q3']].copy().reset_index(drop=True)
qualifying_analisis.insert(2, 'year', qualifying_analisis['raceId'].map(race_year))
qualifying_analisis.insert(4, 'driverName', qualifying_analisis['driverId'].map(piloto_por_id))
qualifying_analisis.insert(6, 'constructorName', qualifying_analisis['constructorId'].map(escuderia_por_id))
qualifying_analisis

,qualifyId,raceId,year,driverId,driverName,constructorId,constructorName,position,q1,q2,q3
0,3326,337,2010,20,Sebastian Vettel,9,Red Bull,1,1:55.029,1:53.883,1:54.101
1,3327,337,2010,13,Felipe Massa,6,Ferrari,2,1:55.313,1:54.331,1:54.242
2,3328,337,2010,4,Fernando Alonso,6,Ferrari,3,1:54.612,1:54.172,1:54.608
3,3329,337,2010,1,Lewis Hamilton,1,McLaren,4,1:55.341,1:54.707,1:55.217
4,3330,337,2010,3,Nico Rosberg,131,Mercedes,5,1:55.463,1:54.682,1:55.241
...,...,...,...,...,...,...,...,...,...,...,...
6407,10547,1144,2024,848,Alexander Albon,3,Williams,16,1:23.821,\N,\N
6408,10548,1144,2024,855,Guanyu Zhou,15,Sauber,17,1:23.880,\N,\N
6409,10549,1144,2024,1,Lewis Hamilton,131,Mercedes,18,1:23.887,\N,\N
6410,10550,1144,2024,861,Franco Colapinto,3,Williams,19,1:23.912,\N,\N
6411,10551,1144,2024,862,Jack Doohan,214,Alpine F1 Team,20,1:24.105,\N,\N

Tenemos ambas tablas listas para continuar el analisis

Vamos primero cuantas carreras finalizo cada piloto. (Luego podemos analizar cuantas finalizo contra las que no. Ese porcentaje nos ayuda tambien a medir talento pero seguiremos centrandonos en carreras finalizadas)

In [267]:
cant_carreras_pilotos = carreras_analisis.groupby(['driverId', 'driverName'])['raceId'].count().reset_index(name='race_count').sort_values('race_count', ascending=False)
cant_carreras_pilotos

    driverId         driverName  race_count
0          1     Lewis Hamilton         276
32       815       Sergio Pérez         242
13        20   Sebastian Vettel         225
34       817   Daniel Ricciardo         217
39       822    Valtteri Bottas         217
..       ...                ...         ...
76       860     Oliver Bearman           3
18        32    Christian Klien           2
66       850  Pietro Fittipaldi           2
67       851        Jack Aitken           1
78       862        Jack Doohan           1

[79 rows x 3 columns]

Observamos que hay pilotos que tienen solo una carrera o muy pocas. Analicemos los datos obtenidos para decidir que pilotos vamos a analizar, siendo mas eficiente tomar aquellos que tienen una cantidad de carreras finalizadas significativas

In [271]:
cant_carreras_pilotos['race_count'].describe().round(2)

count     79.00
mean      66.84
std       67.48
min        1.00
25%       17.50
50%       42.00
75%      110.50
max      276.00
Name: race_count, dtype: float64

Por el momento, no descartaremos pilotos pero si observaremos de los datos que la media es menor a la mediana, ergo los pilotos que mas carreras tienen corrieron exponencialmente mas carreras que los que menos. Es un dato importante a tener en cuenta.